version: '2'

services:
  solr:
    image: solr
    hostname: solr
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
  db:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: superman
       MYSQL_DATABASE: capitolwords
       MYSQL_USER: capitolwords
       MYSQL_PASSWORD: capitolwords
  django:
    build:
      context: .
      dockerfile: cwod_site/Dockerfile.django
    command: python manage.py runserver --noreload 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - CAPWORDS_BASEURL=http://localhost:8000
      - CAPWORDS_HOME=/code
      - CAPWORDS_TMP=/tmp
      - CAPWORDS_LOGS=logs
      - CAPWORDS_SOLR_URL=http://localhost:8983
      - CAPWORDS_SUNLIGHT_APIKEY=foobar
      - DJANGO_SETTINGS_MODULE=/code/settings.py
    links:
      - db
      - solr

volumes:
  solr:
  db_data:
