# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRECParserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
                ('crec_s3_key', models.CharField(max_length=200)),
            ],
        ),
    ]
