FROM python:2.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /cwod_site
WORKDIR /cwod_site
ADD cwod_site /cwod_site
RUN pip install -r requirements.txt
RUN cp /cwod_site/local_settings_docker.py /cwod_site/local_settings.py
EXPOSE 8000
