# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0001_squashed_0004_auto_20170526_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalid',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='legislators.CongressPerson'),
        ),
        migrations.AlterField(
            model_name='term',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='legislators.CongressPerson'),
        ),
    ]
