# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0002_auto_20170526_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congressperson',
            options={'ordering': ('official_full',)},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('start_date',)},
        ),
    ]
