# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0004_auto_20170530_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congressperson',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='congressperson',
            old_name='last_name',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='congressperson',
            old_name='middle_name',
            new_name='middle',
        ),
        migrations.RemoveField(
            model_name='congressperson',
            name='id',
        ),
        migrations.AddField(
            model_name='congressperson',
            name='bioguide_id',
            field=models.CharField(default='foo', max_length=7, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
