# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0005_auto_20170724_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressperson',
            name='official_full',
            field=models.CharField(max_length=50),
        ),
    ]
