# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0007_auto_20170724_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressperson',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
