# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0008_auto_20170724_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='rss_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='congressperson',
            name='birthday',
            field=models.DateField(default=datetime.date(1776, 7, 4)),
        ),
        migrations.AlterField(
            model_name='term',
            name='contact_form',
            field=models.URLField(default=None),
        ),
    ]
