# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0009_auto_20170724_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='contact_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='rss_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
