# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0010_auto_20170724_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
