# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerWordCounts',
            fields=[
                ('bioguide_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('crec_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('named_entities', models.TextField()),
                ('noun_chunks', models.TextField()),
            ],
        ),
    ]
