# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
