# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRECScraperResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
                ('num_crec_files_uploaded', models.IntegerField(default=0)),
            ],
        ),
    ]
